#!/bin/bash

source lib

# DEFAULT_CONFIG=/etc/lit
DEFAULT_CONFIG=default
USER_CONFIG=~/.lit

[ -f $DEFAULT_CONFIG ] && eloademojis $DEFAULT_CONFIG
[ -f $USER_CONFIG ] && eloademojis $USER_CONFIG

while [[ $# -gt 0 ]]; do
    case $1 in
	-h|--help)
	    ehelp
	    exit
	    ;;
	-e|--emojis)
	    eemojis
	    exit
	    ;;
	-f|--file)
	    [ -f $2 ] && eloademojis $2
	    shift
	    shift
	    ;;
	*)
	    POSITIONAL+=("$1")
	    shift
	    ;;
    esac
done
set -- "${POSITIONAL[@]}"

while read line; do
    echo "$line" | sed "`escript`"
done
