#!/bin/bash

declare -A emojis

function eloademojis() {
    while read -r -a line; do
	emojis["${line[@]:1}"]="${line}"
    done < "$1"
}

function escript() {
    local script=''
    while read -r -a line; do
	script+="s/${line[@]:1}/${line}/gI;"
    done < <(for name in "${!emojis[@]}"; do
	echo ${emojis["$name"]} \"$name\"
    done | awk '{ print length - length($1), $0 }' | sort -rn -s | sed -E 's/[^ ]* //' | sed 's/"//g')
    echo $script
}

function ehelp() {
    echo -e '\t👌LITIFY👌 👉 substring replacer'
    echo -e '\t-h to print this help'
    echo -e '\t-e to print emojis and substitutions'
}

function eemojis() {
    echo '-------------------------'
    echo "`escript`"
    echo '-------------------------'
}


DEFAULT_CONFIG=/etc/lit
USER_CONFIG=~/.lit

[ -f $DEFAULT_CONFIG ] && eloademojis $DEFAULT_CONFIG
[ -f $USER_CONFIG ] && eloademojis $USER_CONFIG

while [[ $# -gt 0 ]]; do
    case $1 in
	-h|--help)
	    ehelp
	    exit
	    ;;
	-e|--emojis)
	    eemojis
	    exit
	    ;;
	-f|--file)
	    [ -f $2 ] && eloademojis $2
	    shift
	    ;;
	-s|--spaces)
	    # TODO: implement
	    ;;
	*)
	    POSITIONAL+=("$1")
	    ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

while read line; do
    echo "$line" | sed "`escript`"
done
